name: Bug Report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: 'Steps to reproduce'
      description: 'Steps to reproduce the behavior.'
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: loader-version
    attributes:
      label: 'Loader version'
      description: 'The version of minecraft and the version of the mod loader.'
      placeholder: |
        Minecraft 1.21
        Fabric Loader 0.16.0
      validations:
          required: true
  - type: input
    id: foglock-version
    attributes:
      label: 'FogLock version'
      description: 'FogLock mod version.'
      placeholder: 1.7.0
    validations:
        required: true
  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
    validations:
      required: false
